Repository ESTsoft-Back-end-6th-2nd-project-team3/ESTsoft-2nd-Project, pull requests merged in 2024-11, with the labels that each got.

#5 DB 경로 수정, OAuth2 의존성 추가
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#7 USER API 구현
  src/main/java/com/estsoft/estsoft2ndproject/EsTsoft2ndProjectApplication.java
  src/main/java/com/estsoft/estsoft2ndproject/config/WebSecurityConfig.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/UserController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/temp.java
  src/main/java/com/estsoft/estsoft2ndproject/custonException/AdditionalInformationRequireException.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/Level.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/User.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/member/temp.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/user/RegisterRequest.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/user/UserRequest.java
  src/main/java/com/estsoft/estsoft2ndproject/repository/UserRepository.java
  src/main/java/com/estsoft/estsoft2ndproject/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/sql/Untitled.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
  src/main/resources/templates/registerRequest.html
  src/test/java/com/estsoft/estsoft2ndproject/jsypt/JasyptConfigAESTest.java
Labels: enhancement

#14 댓글 API 구현(좋아요 제외)
  src/main/java/com/estsoft/estsoft2ndproject/config/JpaConfig.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/CommentApiController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/PostApiController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/UserController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/PostController.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/Comment.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/Level.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/comment/CommentRequestDTO.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/comment/CommentResponseDTO.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/comment/ParentCommentResponseDTO.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/comment/temp.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/user/RegisterRequestDTO.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/user/UserRequestDTO.java
  src/main/java/com/estsoft/estsoft2ndproject/repository/CommentRepository.java
  src/main/java/com/estsoft/estsoft2ndproject/service/CommentService.java
  src/main/resources/templates/comment-test.html
  src/main/resources/templates/test-index.html
Labels: enhancement

#19 댓글 UI 모듈 추가 & User 조회 서비스 추가
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/CommentApiController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/UserController.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/Comment.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/comment/CommentListResponseDTO.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/comment/CommentRequestDTO.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/comment/CommentResponseDTO.java
  src/main/java/com/estsoft/estsoft2ndproject/repository/CommentRepository.java
  src/main/java/com/estsoft/estsoft2ndproject/service/CommentService.java
  src/main/java/com/estsoft/estsoft2ndproject/service/UserService.java
  src/main/resources/static/css/base.css
  src/main/resources/templates/fragment/view-comment.html
  src/main/resources/templates/registerRequest.html
  src/main/resources/templates/testHtml/comment-test.html
  src/main/resources/templates/testHtml/login.html
  src/main/resources/templates/testHtml/register.html
  src/main/resources/templates/testHtml/test-index.html
Labels: enhancement

#21 댓글 API를 통해 CRUD 구현 및 작성창 UI 구현
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/CommentApiController.java
  src/main/java/com/estsoft/estsoft2ndproject/repository/CommentRepository.java
  src/main/java/com/estsoft/estsoft2ndproject/service/CommentService.java
  src/main/resources/static/css/base.css
  src/main/resources/templates/fragment/view-comment.html
Labels: enhancement

#23 댓글이 한 개도 존재하지 않을 때 에러가 발생하는 현상 수정
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/CommentApiController.java
  src/main/java/com/estsoft/estsoft2ndproject/repository/CommentRepository.java
  src/main/java/com/estsoft/estsoft2ndproject/service/CommentService.java
  src/main/resources/templates/fragment/view-comment.html
Labels: bug, enhancement

#24 테스트 코드로 가입할 때 프로필 url의 값을 받아오지 못하는 현상 수정, index.html 구조 변경
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/UserController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/PageController.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/user/RegisterRequestDTO.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/user/UserRequestDTO.java
  src/main/resources/static/css/base.css
  src/main/resources/templates/index.html
  src/main/resources/templates/testHtml/register.html
Labels: bug, enhancement

#27 User 객체 및 서비스, 접근제어, 접근 예시
  src/main/java/com/estsoft/estsoft2ndproject/config/WebSecurityConfig.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/CommentApiController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/UserController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/CustomErrorController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/PageController.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/user/CustomUserDetails.java
  src/main/java/com/estsoft/estsoft2ndproject/exception/CustomAccessDeniedHandler.java
  src/main/java/com/estsoft/estsoft2ndproject/service/CommentService.java
  src/main/java/com/estsoft/estsoft2ndproject/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/templates/index.html
Labels: enhancement

#31 활성화된 게시글만 출력, 댓글에서 관리자일 때 삭제 표시, 어노테이션 수정
  src/main/java/com/estsoft/estsoft2ndproject/config/WebSecurityConfig.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/CommentApiController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/PostApiController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/PageController.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/mypage/PostResponseDTO.java
  src/main/java/com/estsoft/estsoft2ndproject/repository/PostRepository.java
  src/main/java/com/estsoft/estsoft2ndproject/service/MyPageService.java
  src/main/java/com/estsoft/estsoft2ndproject/service/PostService.java
  src/main/resources/static/css/base.css
  src/main/resources/static/images/logo.png
  src/main/resources/templates/fragment/search-all.html
  src/main/resources/templates/fragment/view-comment.html
  src/main/resources/templates/index.html
  src/test/java/com/estsoft/estsoft2ndproject/controller/api/MyPageControllerTest.java
Labels: enhancement

#33 베스트 게시글 클릭 시 테스트 페이지로 이동되는 현상 수정
  src/main/resources/templates/fragment/bulletin-board-list.html
  src/main/resources/templates/fragment/category-best.html
  src/main/resources/templates/index.html
Labels: enhancement

#34 mypage
  build.gradle
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/ImageController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/MyPageController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/UserController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/PageController.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/Level.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/Objective.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/comment/temp.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/mypage/UserInfoRequestDTO.java
  src/main/java/com/estsoft/estsoft2ndproject/domain/dto/mypage/temp.java
  src/main/java/com/estsoft/estsoft2ndproject/repository/ObjectiveRepository.java
  src/main/java/com/estsoft/estsoft2ndproject/repository/UserRepository.java
  src/main/java/com/estsoft/estsoft2ndproject/service/MyPageService.java
  src/main/java/com/estsoft/estsoft2ndproject/service/ObjectiveService.java
  src/main/java/com/estsoft/estsoft2ndproject/service/PostService.java
  src/main/java/com/estsoft/estsoft2ndproject/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/static/css/base.css
  src/main/resources/static/js/edit-profile.js
  src/main/resources/static/js/mypage-profile.js
  src/main/resources/static/js/objectiveChart.js
  src/main/resources/templates/comment-test.html
  src/main/resources/templates/edit-profile.html
  src/main/resources/templates/fragment/edit-objective.html
  src/main/resources/templates/fragment/edit-profile.html
  src/main/resources/templates/fragment/my-objective.html
  src/main/resources/templates/fragment/mypage-profile.html
  src/main/resources/templates/fragment/participated-challenge.html
  src/main/resources/templates/fragment/register.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage-profile.html
  src/main/resources/templates/testHtml/register.html
  src/main/resources/templates/testHtml/test-index.html
Labels: enhancement

#37 등급 관리 fix
  src/main/resources/templates/index.html
Labels: bug, enhancement

#39 내 목표 추가 항목 순서 수정
  src/main/resources/templates/index.html
Labels: bug

#40 챌린지 게시글 조회수 증가 추가
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/PageController.java
Labels: bug

#42 bug fix
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/UserController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/PageController.java
  src/main/java/com/estsoft/estsoft2ndproject/service/UserService.java
  src/main/resources/static/css/base.css
  src/main/resources/templates/fragment/profile-manage.html
  src/main/resources/templates/fragment/view-comment.html
  src/main/resources/templates/index.html
Labels: bug, enhancement

#45 관리자페이지
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/AdminController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/AdminTest.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/BoardController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/LoginController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/ObjectTest.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/PageController.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/main/SideController.java
  src/main/java/com/estsoft/estsoft2ndproject/repository/PostRepository.java
  src/main/java/com/estsoft/estsoft2ndproject/repository/UserRepository.java
  src/main/java/com/estsoft/estsoft2ndproject/service/AdminService.java
  src/main/java/com/estsoft/estsoft2ndproject/service/PostService.java
  src/main/java/com/estsoft/estsoft2ndproject/service/UserService.java
  src/main/resources/static/css/base.css
  src/main/resources/templates/fragment/admin-board-list.html
  src/main/resources/templates/fragment/admin-user-list.html
  src/main/resources/templates/fragment/view-comment.html
  src/main/resources/templates/fragment/written-board-list.html
  src/main/resources/templates/index.html
Labels: enhancement

#47 이미지 저장 경로 수정
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/ImageController.java
Labels: bug

#49 이미지 업로드 수정
  src/main/java/com/estsoft/estsoft2ndproject/config/WebMvcConfig.java
  src/main/java/com/estsoft/estsoft2ndproject/controller/api/ImageController.java
  src/main/resources/application.yml
Labels: bug, enhancement

#50 리드미 수정
  README.md
Labels: documentation

#51 보안 설정 수정
  src/main/java/com/estsoft/estsoft2ndproject/config/WebSecurityConfig.java
Labels: enhancement
